### ISSUE TITLE
can sdcup models be called by transformers interface?

### ISSUE THREAD

**Issue by michaelxu1107** [alibaba/AliceMind#46]
can sdcup models be called by transformers interface? such as TapasForQuestionAnswering, thanks

**Comment by grygg** [comment]
Hello, you can convert the model format to huggingface using this script, https://github.com/dbiir/UER-py/blob/master/scripts/convert_bert_from_uer_to_huggingface.py
Well, I also suggest you apply the offered code.

**Comment by michaelxu1107** [comment]
hello, thanks for reply, but when I use script show above to convert model, it shows error below

$ python convert_bert_from_uer_to_huggingface.py --input_model_path "./sdcup_base_model.bin-50000" --output_model_path "./pytorch_model.bin"
Traceback (most recent call last):
  File "/home/smart_qa/sdcup/convert_bert_from_uer_to_huggingface.py", line 82, in <module>
    main()
  File "/home/smart_qa/sdcup/convert_bert_from_uer_to_huggingface.py", line 58, in main
    output_model["bert.embeddings.word_embeddings.weight"] = input_model["embedding.word_embedding.weight"]
KeyError: 'embedding.word_embedding.weight'

**Comment by grygg** [comment]
You can print the key names of the loaded model, maybe you need alignment the key names.
